name: clean_architecture_tdd_course
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  # get_it: ^3.1.0
  get_it: ^7.6.4
  # Bloc for state management
  # flutter_bloc: ^3.0.0
  flutter_bloc: ^8.1.3
  # Value equality
  # equatable: ^1.0.1
  equatable: ^2.0.5
  # Functional programming thingies
  # dartz: ^0.8.9
  dartz: ^0.10.1
  # Remote API
  # data_connection_checker: ^0.3.4
  # http: ^0.12.0+3
  http: ^1.1.0
  # Local cache
  # shared_preferences: ^0.5.6
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mockito: ^4.1.
  mockito: ^5.4.2

flutter:
  uses-material-design: true
